kind: Deployment
apiVersion: apps/v1
metadata:
  name: tcc-frontend
  namespace: TCCEspecialista
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcc-frontend
  template:
    metadata:
      labels:
        app: tcc-frontend
    spec:
      containers:
        - name: mainapp
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 64m
              memory: 128Mi
            requests:
              cpu: 32m
              memory: 128Mi     
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 4
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            timeoutSeconds: 4
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
